### ISSUE TITLE
Get app to boot to root path

### ISSUE THREAD

**Issue by robzolkos** [wesley974/admin-rewrite-upgrade#4]

**Comment by wesley974** [comment]
The app was run using this command line : `/usr/local/bin/mongrel_rails start -c ${_DEFAULT}/admin -p 4213 -a 127.0.0.1 -d -e production -P $_DEFAULT/admin/log/mongrel.pid 2> /dev/null`

Then **Nginx** deliver app through a Upstream.

**Comment by robzolkos** [comment]
This will change to nginx delivering the app through `puma` upstream (assuming you want to keep things modern).   I don't think `mongrel_rails` is up to date anymore (last updated 2008) https://github.com/mongrel/mongrel

**Comment by robzolkos** [comment]
App now boots and gets through the `getting_started` and `login` phase.   Tests added.  This gives us a start to now keep adding tests.

Closed by https://github.com/wesley974/admin-rewrite-upgrade/pull/7

**Comment by wesley974** [comment]
Awesome job @robzolkos ! Many thank's!  🥇
